export const PASSENGER_TYPES = {
  SENIOR_CITIZEN: 'SENIOR_CITIZEN',
  ADULT: 'ADULT',
  KID: 'KID',
};

export const STATION_NAMES = {
  AIRPORT: 'AIRPORT',
  CENTRAL: 'CENTRAL',
};

export const FARES = {
  [PASSENGER_TYPES.ADULT]: 200,
  [PASSENGER_TYPES.SENIOR_CITIZEN]: 100,
  [PASSENGER_TYPES.KID]: 50,
};

export const ERROR_CODES = {
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
};
